### ISSUE TITLE
Compared with center loss, Island loss only adds a constant term, is this really work?

### ISSUE THREAD

**Issue by Ostnie** [ShuvenduBikash/IslandLoss#2]
![image](https://user-images.githubusercontent.com/31840090/50369987-8346ad00-05d9-11e9-975f-fc78d53edf3c.png)
the 
![image](https://user-images.githubusercontent.com/31840090/50370007-c43ec180-05d9-11e9-9af5-44314170aa2f.png) is a constant term and don't work in backward propagation, so I wonder to know the effect of it.
Besides this, why do formulas add one at the end?
Hope for your answer, thank you!

**Comment by ShuvenduRoy** [comment]
How can the mentioned term be constant?

**Comment by Ostnie** [comment]
em.... I found I was wrong. However, I still puzzled about the +1 in the last
